# Site settings
author: Cho Hughes
title: Navigating The Confusing, But Fun, Road Of Software Engineering
header-img: img/home-bg.png
email: kchohee0630@gmail.com
copyright_name: Cho Hughes
description: > # this means to ignore newlines until "baseurl:"
  My Endeavor To Survive This Crazy Thing Called Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kchohee

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
